Blog_Project/Controllers/SocialMediaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Blog_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SocialMediaController : Controller
    {
        SocialMediaManager socialMediaManager = new SocialMediaManager(new EfSocialMediaDal());
        public IActionResult Index()
        {
            var values = socialMediaManager.TGetList();
            return View(values);
        }

        public IActionResult DeleteSocialMedia(int id)
        {
            var values = socialMediaManager.TGetByID(id);
            socialMediaManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddSocialMedia()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSocialMedia(SocialMedia socialMedia)
        {
            socialMediaManager.TAdd(socialMedia);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSocialMedia(int id)
        {
            var values = socialMediaManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditSocialMedia(SocialMedia socialMedia)
        {
            socialMediaManager.TUpdate(socialMedia);
            return RedirectToAction("Index");
        }
    }
}

Blog_Project/Views/SocialMedia/AddSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia

@{
    ViewData["Title"] = "AddSocialMedia";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    var icons = new List<SelectListItem>
    {
        new SelectListItem { Value = "fab fa-facebook", Text = "Facebook" },
        new SelectListItem { Value = "fab fa-twitter", Text = "Twitter" },
        new SelectListItem { Value = "fab fa-instagram", Text = "Instagram" },
        new SelectListItem { Value = "fab fa-linkedin", Text = "LinkedIn" },
        new SelectListItem { Value = "fab fa-youtube", Text = "YouTube" },
        new SelectListItem { Value = "fab fa-pinterest", Text = "Pinterest" },
        new SelectListItem { Value = "fab fa-twitch", Text = "Twitch" },
        new SelectListItem { Value = "fab fa-vimeo", Text = "Vimeo" },
        new SelectListItem { Value = "fab fa-soundcloud", Text = "SoundCloud" },
        new SelectListItem { Value = "fab fa-telegram", Text = "Telegram" },
        new SelectListItem { Value = "fab fa-steam", Text = "Steam" },
        new SelectListItem { Value = "fab fa-slack", Text = "Slack" },
        new SelectListItem { Value = "fab fa-tumblr", Text = "Tumblr" },
        new SelectListItem { Value = "fab fa-reddit", Text = "Reddit" },
        new SelectListItem { Value = "fab fa-vk", Text = "VK" },
        new SelectListItem { Value = "fab fa-dribbble", Text = "Dribbble" },
        new SelectListItem { Value = "fab fa-behance", Text = "Behance" },
        new SelectListItem { Value = "fab fa-flickr", Text = "Flickr" }
    };

    var status = new List<SelectListItem>
    {
        new SelectListItem { Value = "True", Text = "Aktif" },
        new SelectListItem { Value = "False", Text = "Pasif" }
    };
}

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card mb-4">
        <h5 class="card-header">Sosyal Medya Ekleme Paneli</h5>
        <div class="card-body">
            <form class="forms-sample" method="post">
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">Başlık</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x => x.Name, new SelectList(icons, "Value", "Text"), new { @class = "form-control" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-search-input" class="col-md-2 col-form-label">Url</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">Durum</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x => x.Status, new SelectList(status, "Value", "Text"), new { @class = "form-control" })
                    </div>
                </div>
                <div class="button-class" style="margin-top: 30px">
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "SocialMedia")'">İptal</button>
                </div>
            </form>
        </div>
    </div>
</div>

Blog_Project/Views/SocialMedia/EditSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia

@{
    ViewData["Title"] = "EditSocialMedia";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    var icons = new List<SelectListItem>
    {
        new SelectListItem { Value = "fab fa-facebook", Text = "Facebook" },
        new SelectListItem { Value = "fab fa-twitter", Text = "Twitter" },
        new SelectListItem { Value = "fab fa-instagram", Text = "Instagram" },
        new SelectListItem { Value = "fab fa-linkedin", Text = "LinkedIn" },
        new SelectListItem { Value = "fab fa-youtube", Text = "YouTube" },
        new SelectListItem { Value = "fab fa-pinterest", Text = "Pinterest" },
        new SelectListItem { Value = "fab fa-twitch", Text = "Twitch" },
        new SelectListItem { Value = "fab fa-vimeo", Text = "Vimeo" },
        new SelectListItem { Value = "fab fa-soundcloud", Text = "SoundCloud" },
        new SelectListItem { Value = "fab fa-telegram", Text = "Telegram" },
        new SelectListItem { Value = "fab fa-steam", Text = "Steam" },
        new SelectListItem { Value = "fab fa-slack", Text = "Slack" },
        new SelectListItem { Value = "fab fa-tumblr", Text = "Tumblr" },
        new SelectListItem { Value = "fab fa-reddit", Text = "Reddit" },
        new SelectListItem { Value = "fab fa-vk", Text = "VK" },
        new SelectListItem { Value = "fab fa-dribbble", Text = "Dribbble" },
        new SelectListItem { Value = "fab fa-behance", Text = "Behance" },
        new SelectListItem { Value = "fab fa-flickr", Text = "Flickr" }
    };

    var status = new List<SelectListItem>
    {
        new SelectListItem { Value = "True", Text = "Aktif" },
        new SelectListItem { Value = "False", Text = "Pasif" }
    };
}

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card mb-4">
        <h5 class="card-header">Sosyal Medya Düzenleme Paneli</h5>
        <div class="card-body">
            <form class="forms-sample" method="post">
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">ID</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(x => x.SocialMediaID, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">Başlık</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x => x.Name, new SelectList(icons, "Value", "Text"), new { @class = "form-control" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-search-input" class="col-md-2 col-form-label">Url</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">Durum</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x => x.Status, new SelectList(status, "Value", "Text"), new { @class = "form-control" })
                    </div>
                </div>
                <div class="button-class" style="margin-top: 30px">
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "SocialMedia")'">İptal</button>
                </div>
            </form>
        </div>
    </div>
</div>

Blog_Project/Views/SocialMedia/Index.cshtml
@using EntityLayer.Concrete
@model List<SocialMedia>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card">
        <div class="table-responsive text-nowrap">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Başlık</th>
                        <th>Url</th>
                        <th>Durum</th>
                        <th>Sil</th>
                        <th>Güncelle</th>
                    </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td><strong></strong>@item.SocialMediaID</td>
                            <td>@item.Name</td>
                            <td style="color:blueviolet"><a href="@item.Url" target="_blank">Tıkla</a></td>
                            @if (item.Status == true)
                            {
                                <td><span class="label label-success" style="color:green; font-weight:bold">Aktif</span></td>
                            }
                            else
                            {
                                <td><span class="label label-warning" style="color: red; font-weight: bold">Pasif</span></td>
                            }
                            <td><a href="/SocialMedia/DeleteSocialMedia/@item.SocialMediaID" class="btn btn-outline-danger" onclick="return confirm('Gerçekten silmek istiyor musunuz?')"><span class="tf-icons bx bx-error-alt"></span>&nbsp; Sil</a></td>
                            <td><a href="/SocialMedia/EditSocialMedia/@item.SocialMediaID" class="btn btn-outline-success"><span class="tf-icons bx bx-pencil"></span>&nbsp; Güncelle</a></td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <br />
    <div style="text-align: left;">
        <a href="/SocialMedia/AddSocialMedia/" class="btn btn-outline-info">
            <span class="tf-icons bx bx-clipboard"></span>Sosyal Medya Ekle
        </a>
    </div>
</div>