Blog_Project/Controllers/AwardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Blog_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AwardsController : Controller
    {
        AwardsManager awardsManager = new AwardsManager(new EfAwardsDal());
        public IActionResult Index()
        {
            var values = awardsManager.TGetList();
            return View(values);
        }

        public IActionResult DeleteAwards(int id)
        {
            var values = awardsManager.TGetByID(id);
            awardsManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddAwards()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddAwards(Awards awards)
        {
            awardsManager.TAdd(awards);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditAwards(int id)
        {
            var values = awardsManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditAwards(Awards awards)
        {
            awardsManager.TUpdate(awards);
            return RedirectToAction("Index");
        }
    }
}

Blog_Project/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Blog_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());
        public IActionResult Index()
        {
            var values = experienceManager.TGetList();
            return View(values);
        }

        public IActionResult DeleteExperience(int id)
        {
            var values = experienceManager.TGetByID(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddExperience()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditExperience(int id)
        {
            var values = experienceManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

Blog_Project/Views/Awards/AddAwards.cshtml
@model EntityLayer.Concrete.Awards

@{
    ViewData["Title"] = "AddAwards";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@* <div class="container-xxl flex-grow-1 container-p-y">

        <div class="row">
            <div class="demo-vertical-spacing demo-only-element col-md-8 ">
                <form class="forms-sample" method="post">
                    <div class="input-group input-group-merge">
                        @Html.TextBoxFor(x => x.JobTitle, new { @class = "form-control" })
                    </div>
                    <div class="input-group input-group-merge">
                        @Html.TextBoxFor(x => x.WorkPlace, new { @class = "form-control" })
                    </div>
                    <div class="input-group input-group-merge">
                        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                    </div>
                    <div class="input-group input-group-merge">
                        @Html.TextAreaFor(x => x.Description, 8, 3, new { @class = "form-control" })
                    </div>
                    <br />
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Experience")'">İptal</button>
                </form>
            </div>
        </div>
    </div> *@


<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card mb-4">
        <h5 class="card-header">Ödül &amp; Sertifika Ekleme Paneli</h5>
        <div class="card-body">
            <form class="forms-sample" method="post">
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">Ödül Başlığı</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x => x.Name, new SelectList(new List<string> { "", "1", "2", "3", "4", "5"}), new { @class = "form-control" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-search-input" class="col-md-2 col-form-label">Başarı</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(x => x.GradePlace, new { @class = "form-control" })
                    </div>
                </div>
                <div class="button-class" style="margin-top: 30px">
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Awards")'">İptal</button>
                </div>
            </form>
        </div>
    </div>
</div>

Blog_Project/Views/Awards/EditAwards.cshtml
@model EntityLayer.Concrete.Awards

@{
    ViewData["Title"] = "EditAwards";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card mb-4">
        <h5 class="card-header">Ödül &amp; Sertifika Düzenleme Paneli</h5>
        <div class="card-body">
            <form class="forms-sample" method="post">
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">ID</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(x => x.AwardsID, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-text-input" class="col-md-2 col-form-label">Ödül Başlığı</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x => x.Name, new SelectList(new List<string> { "","1", "2", "3", "4", "5" }), new { @class = "form-control" })
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="html5-search-input" class="col-md-2 col-form-label">Başarı</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(x => x.GradePlace, new { @class = "form-control" })
                    </div>
                </div>
                <div class="button-class" style="margin-top: 30px">
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Awards")'">İptal</button>
                </div>
            </form>
        </div>
    </div>
</div>

Blog_Project/Views/Awards/Index.cshtml
@using EntityLayer.Concrete
@model List<Awards>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-xxl flex-grow-1 container-p-y">
        <div class="card">
            <div class="table-responsive text-nowrap">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ödül Başlığı</th>
                            <th>Başarı</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td><strong></strong>@item.AwardsID</td>
                                <td>@item.Name</td>
                                @if (item.GradePlace == "1")
                                {
                                    <td style="color: gold">@item.GradePlace</td>
                                }
                                else if (item.GradePlace == "2")
                                {
                                    <td style="color: seagreen">@item.GradePlace</td>
                                }
                                else
                                {
                                    <td style="color: darkviolet">@item.GradePlace</td>
                                }
                                <td><a href="/Awards/DeleteAwards/@item.AwardsID" class="btn btn-outline-danger" onclick="return confirm('Gerçekten silmek istiyor musunuz?')"><span class="tf-icons bx bx-error-alt"></span>&nbsp; Sil</a></td>
                                <td><a href="/Awards/EditAwards/@item.AwardsID" class="btn btn-outline-success"><span class="tf-icons bx bx-pencil"></span>&nbsp; Güncelle</a></td>

                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    <br />
    <div style="text-align: left;">
        <a href="/Awards/AddAwards/" class="btn btn-outline-info">
            <span class="tf-icons bx bx-clipboard"></span>&nbsp; Ödül &amp; Sertifika Ekle
        </a>
    </div>
</div>